# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

defaults: &defaults
  docker:
    - image: circleci/node:10.1

version: 2
jobs:
  docker-compose:
    <<: *defaults
    steps:
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - persist_to_workspace:
          root: /usr/local/bin
          paths: docker-compose

  install:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - leaistic-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - leaistic-dependencies-

      - run: yarn
      # Persist the specified paths into the workspace for usage in later jobs
      - persist_to_workspace:
          root: .
          paths: .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up -d
            # docker-compose will start 2 containers, the one with service will be named `es`
            # we start another container with curl in the same network as `es`, this way we have
            # all exposed ports from `es` available on `localhost` in this new container
            docker run --network container:es \
              appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:8080/contacts/test
      # Run tests
      - run: yarn test

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      # Run lint
      - run: yarn lint

  release-dry-run:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: release
          command: npm run semantic-release --dry-run || true
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: release
          command: npm run semantic-release || true

workflows:
  version: 2
  all:
    jobs:
      - docker-compose
      - install:
          requires:
            - docker-compose
      - test:
          requires:
            - install
      - lint:
          requires:
            - install
      - release-dry-run:
          requires:
            - test
            - lint
          filters:
            branches:
              ignore: master
      - release:
          requires:
            - test
            - lint
          filters:
            branches:
              only: master
